mutation InitiateWebauthnLogin($input: InitiateWebauthnLoginInput!) {
  initiateWebauthnLogin(input: $input)
}

mutation CompleteWebauthnLogin($input: CompleteWebauthnLoginInput!) {
  completeWebauthnLogin(input: $input)
}
