mutation InitiateWebauthnRegistration {
  initiateWebauthnRegistration
}

mutation CompleteWebauthnRegistration(
  $input: CompleteWebauthnRegistrationInput!
) {
  completeWebauthnRegistration(input: $input)
}
