schema: ../backend/api/graph/schema.graphqls
documents: src/**/*.gql
extensions:
  codegen: # https://graphql-code-generator.com/
    overwrite: true
    generates:
      src/types/graphql.gen.ts:
        plugins:
          - typescript
          - typescript-resolvers
        config:
          enumsAsTypes: true
          namingConvention: keep
          avoidOptionals: true
      src/:
        preset: near-operation-file
        presetConfig:
          extension: .gen.ts
          baseTypesPath: types/graphql.gen.ts
        plugins:
          - typescript-operations
          - typescript-react-apollo
        config:
          gqlImport: "@apollo/client#gql"
          constEnums: true
          reactApolloVersion: 3
          withComponent: false
          withHOC: false
          withHooks: true
          enumsAsTypes: true
          namingConvention: keep
          avoidOptionals: true
          preResolveTypes: true
