// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	UserName string `json:"userName"`
}

type CompleteWebauthnLoginInput struct {
	Credential string `json:"credential"`
	Email      string `json:"email"`
}

type CompleteWebauthnRegistrationInput struct {
	Credential string `json:"credential"`
}

type CreateAccountInput struct {
	Email    string `json:"email"`
	UserName string `json:"userName"`
}

type InitiateWebauthnLoginInput struct {
	Email string `json:"email"`
}
